alias: System - Upgrade available
id: 'a3f210ad-0587-4ed2-a5cd-a912d38ad3ee'
description: 'DevOps task to create new issue in GitHub when an update is available.'
initial_state: true
mode: single

trigger:

  # Use the updater integration to trigger the automation.
  - platform: state
    entity_id: binary_sensor.updater
    to: 'on'

  # Daily reminder in case the update still hasn't been done.
  - platform: time
    at: '10:30:00'

  # The version integration seems to be much more responsive.
  - platform: template
    value_template: "{{ states('sensor.version_latest') > states('sensor.version_current') }}"

condition:

  condition: and
  conditions:

    # Ensure a GitHub issue hasn't been created already (avoids duplicate issues being created).
    - condition: template
      value_template: "{{ state_attr('sensor.github_upgrade_issue','number') == 'None' }}"

    # Updater or version sensor indicate there is an upgrade available.
    - condition: or
      conditions:

      - condition: state
        entity_id: binary_sensor.updater
        state: 'on'

      - condition: template
        value_template: "{{ states('sensor.version_latest') > states('sensor.version_current') }}"

action:

  # Create a persistent notification.
  - service: persistent_notification.create
    data_template:
      title: "Home Assistant {{ states('sensor.version_latest') }} now available"
      message: >-
        There is a Home Assistant upgrade available.
        Version {{ states('sensor.version_latest') }} has been released. Current version {{ states('sensor.version_current') }}.
        Release notes available via {{ state_attr('binary_sensor.updater','release_notes') }}.
      notification_id: home_assistant_upgrade

  # Call my GiHub rest command to create a new issue in GitHub.
  - service: rest_command.github_new_issue_upgrade
    data_template:
      current_version: "{{ states('sensor.version_current') }}"
      upgrade_version: "{{ states('sensor.version_latest') }}"
      release_notes: "{{ state_attr('binary_sensor.updater','release_notes') }}"

# Related
# https://github.com/jcallaghan/home-assistant-config/issues/105

# //TODO actionable alert that kicks off Home Assistant stop, docker pull and Home Assistant start
# //TODO include the version number in the title without breaking the upgrade issue rest sensor as the rest sensor does a match on the issue title.
# //TODO decide if this should be for each minor release or stick to major releases.
